- name: conditions
  hosts: node
  become: yes
  tasks:
  - name: check user exist or not
    ansibile.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
      msg: "User info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: user.RC != 0 #CONDITION

  - name: say hello
    ansible.builtin.debug:
      msg: "welcome to devopswithmsvs"
