- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exist or not
    ansbile.builtin.command: id user
    register: USER
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
    msg: "User info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.RC != 0 #CONDITION

  - name: say hello
    ansible.builtin.debug:
    msg: "welcome to devopswithmsvs"
